# Generated by Django 2.2.4 on 2019-09-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GMP2CJU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('flight_section', models.CharField(choices=[('김포(GMP) - 부산(PUS)', '김포(GMP) - 부산(PUS)'), ('김포(GMP) - 제주(CJU)', '김포(GMP) - 제주(CJU)'), ('부산(PUS) - 제주(CJU)', '부산(PUS) - 제주(CJU)'), ('부산(PUS) - 김포(GMP)', '부산(PUS) - 김포(GMP)'), ('제주(CJU) - 김포(GMP)', '제주(CJU) - 김포(GMP)'), ('제주(CJU) - 부산(PUS)', '제주(CJU) - 부산(PUS)')], max_length=300)),
                ('flight_number', models.CharField(choices=[('KE1201,B737-800', 'KE1201,B737-800'), ('KE1203,B737-220ER', 'KE1203,B737-220ER'), ('KE1205,A330-300', 'KE1205,A330-300'), ('KE1209,B737-900', 'KE1209,B737-900'), ('KE1211,B737-200ER', 'KE1211,B737-200ER'), ('KE1213,A330-200', 'KE1213,A330-200'), ('KE1215,A220-300', 'KE1215,A220-300'), ('KE1217,B777-200ER', 'KE1217,B777-200ER'), ('KE1221,A220-300', 'KE1221,A220-300'), ('KE1223,A220-300', 'KE1223,A220-300')], max_length=300)),
                ('special_fare', models.IntegerField()),
                ('normal_fare', models.IntegerField()),
            ],
        ),
    ]
