# Generated by Django 2.2.4 on 2019-09-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_cousrse_search', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GMP2CJU',
            new_name='GmptoCju',
        ),
    ]
