# Generated by Django 2.2.1 on 2019-10-23 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_cousrse_search', '0003_auto_20190915_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoAll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_departure_time', models.DateTimeField()),
                ('cargo_arrival_time', models.DateTimeField()),
                ('cargo_flight_section', models.CharField(choices=[('김포(GMP) - 제주(CJU)', '김포(GMP) - 제주(CJU)')], max_length=300)),
                ('cargo_flight_number', models.CharField(choices=[('KE1201,B737-800', 'KE1201,B737-800'), ('KE1203,B737-220ER', 'KE1203,B737-220ER'), ('KE1205,A330-300', 'KE1205,A330-300'), ('KE1209,B737-900', 'KE1209,B737-900'), ('KE1211,B737-200ER', 'KE1211,B737-200ER'), ('KE1213,A330-200', 'KE1213,A330-200'), ('KE1215,A220-300', 'KE1215,A220-300'), ('KE1217,B777-200ER', 'KE1217,B777-200ER'), ('KE1221,A220-300', 'KE1221,A220-300'), ('KE1223,A220-300', 'KE1223,A220-300')], max_length=300)),
                ('cargo_special_fare', models.IntegerField()),
                ('cargo_normal_fare', models.IntegerField()),
            ],
        ),
    ]
