# Generated by Django 2.2.1 on 2019-10-23 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_cousrse_search', '0005_auto_20191023_0904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cargoall',
            old_name='cargo_arrival_time',
            new_name='cargo_arrival_test',
        ),
        migrations.RenameField(
            model_name='cargoall',
            old_name='cargo_departure_time',
            new_name='cargo_departure_test',
        ),
        migrations.RenameField(
            model_name='cargoall',
            old_name='cargo_flight_number',
            new_name='cargo_flight_number_test',
        ),
        migrations.RenameField(
            model_name='cargoall',
            old_name='cargo_flight_section',
            new_name='cargo_flight_section_test',
        ),
        migrations.RenameField(
            model_name='cargoall',
            old_name='cargo_normal_fare',
            new_name='cargo_normal_fare_test',
        ),
        migrations.RenameField(
            model_name='cargoall',
            old_name='cargo_special_fare',
            new_name='cargo_special_fare_test',
        ),
    ]
