# Generated by Django 2.2.4 on 2019-09-08 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='companay_spot',
            new_name='company_spot',
        ),
    ]
