# Generated by Django 2.2.4 on 2019-09-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20190908_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='birth',
            field=models.DateField(verbose_name='생년월일'),
        ),
    ]
