# Generated by Django 2.2.1 on 2019-11-20 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0005_auto_20191120_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
