# Generated by Django 2.2.7 on 2019-11-27 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reg_user', '0002_reg_user_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg_user',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reg_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
