# Generated by Django 2.2.4 on 2019-09-15 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Airline_Reservation',
            new_name='Airline_Reserv',
        ),
    ]
