# Generated by Django 2.2.4 on 2019-09-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline_reservation', '0002_auto_20190915_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline_reserv',
            name='arrival_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='airline_reserv',
            name='departure_time',
            field=models.DateTimeField(),
        ),
    ]
