# Generated by Django 3.0rc1 on 2019-12-12 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('main_address', models.CharField(max_length=1000)),
                ('sub_address', models.CharField(max_length=1000)),
                ('company', models.CharField(max_length=500)),
                ('depart', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ('register_created',),
            },
        ),
    ]
