# Generated by Django 3.0 on 2019-12-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AirlineReservationApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airschedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_created', models.DateTimeField(auto_now_add=True)),
                ('arrival_time', models.DateTimeField(max_length=500)),
                ('departure_time', models.DateTimeField(max_length=500)),
                ('navigation_section', models.CharField(max_length=100)),
                ('operating_time', models.CharField(max_length=100)),
                ('airplane_type', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('schedule_created',),
            },
        ),
    ]
